name: Build and test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    - name: Get swift version
      run: swift --version # Swift 5.7.2
    - name: Build PagerTabStrip
      run: xcodebuild build -workspace PagerTabStripView.xcworkspace -scheme PagerTabStrip
    - name: Build Example App
      run: >
        xcodebuild build -workspace PagerTabStripView.xcworkspace -scheme Example
        CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    - name: Run tests
      run: >
          xcodebuild test -workspace PagerTabStripView.xcworkspace -scheme PagerTabStrip
          -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
    - name: Run linter
      run: swiftlint
